### ISSUE TITLE
Suggestion, moonbeam

### ISSUE THREAD

**Issue by qkum** [gelatodigital/automate#66]
hello there, heroes of defi.

i would like to automate the staking of my staking rewards (compounding) on moonbeam/GLMR.

here is the link to the staking contract: https://moonbeam.moonscan.io/address/0x0000000000000000000000000000000000000800#writeContract
(function 8: delegator_bond_more)

maybe make it possible to split the rewards up in 3 portions (20 tokens / 3) and stake 33% of the rewards on collator/node #1, 33% on collator/node #2, and 33% on collator/node #3. (i have spread my staked tokens over 3 collators/nodes for more stable returns/less randomness in rewards)

the problem is that im too n00b to figure out how to do it myself, and you guys have not yet gotten to the task of writing the code to do so.

i actually only write this to tell you that i think that everybody on moonbeam would appreciate it greatly if this function/service got added to the Gelato UI (https://app.gelato.network/) service/function list in a not so distant future :)

have a great summer frens 🥇

**Comment by qkum** [comment]
i just realised that it likely would require that i somehow write a smart-contract that:

#1 hold my staked GLMR tokens.
#2 got a function that counts the free GLMR tokens in the wallet (rewards).
#3 delegates/stakes the rewards over 3 different nodes/collators.
#4 the gelato smart-contract calls this function on the smart-contract containing the staked GLMR.

i guess the other protocol/project where you guys already had written the code for compounding staking rewards. was possible because the stakes are wrapped/encapsulated already, and contains a function that you just call? (like clicking on a pre-made button)

never the less im sure you guys & gals can help make this a friction-less possibility long term 🎉

**Comment by goums** [comment]
Closing this has moonbeam support is deprecated on Automate
